### PR TITLE
Articles page

### PR DESCRIPTION
**Pull request by sakshi2407**
Added articles page

### CODE REVIEW

**Comment by gopivaibhav** [comment]
Great work @sakshi2407 !! Also remember to add the issue number with the respective link for it in the description of PR which is a good practice of making PR in open source.

Example- This PR solves the [issue#2](https://github.com/gopivaibhav/SPARK-website/issues/2)

**Comment by sakshi2407** [comment]
> Great work @sakshi2407 !! Also remember to add the issue number with the respective link for it in the description of PR which is a good practice of making PR in open source.
> 
> Example- This PR solves the [issue#2](https://github.com/gopivaibhav/SPARK-website/issues/2)

Ok sir, will do from next time onwards.

**Comment by gopivaibhav** [comment]
Add 5 article cards using this [code](https://codepen.io/shshaw/pen/vjJEby)

**Comment by sakshi2407** [comment]
> Add 5 article cards using this [code](https://codepen.io/shshaw/pen/vjJEby)

https://user-images.githubusercontent.com/99481336/198813599-d9fa8e3e-74c0-4e76-8552-209b45e632ef.mp4
@gopivaibhav sir, I've been working on this yesterday, please check it once, if you don't find it right, then I can start working on the code that you shared.

**Comment by gopivaibhav** [comment]
> 
> 
> 
> 
> > Add 5 article cards using this [code](https://codepen.io/shshaw/pen/vjJEby)
> 
> https://user-images.githubusercontent.com/99481336/198813599-d9fa8e3e-74c0-4e76-8552-209b45e632ef.mp4
> @gopivaibhav sir, I've been working on this yesterday, please check it once, if you don't find it right, then I can start working on the code that you shared.

It was nice but would only look better if we had around 10 articles, which is not our case as we only have 5 articles.
So, I will prefer the code which I've shared

**Comment by gopivaibhav** [comment]
Also, add a "Read More" button to every card which should be placed in the bottom and when someone clicks on it, It should redirect to the new page with detailed article page @sakshi2407

**Comment by gopivaibhav** [comment]
Closing this as we don't want this design

**Pull request closed without merging**
