### PR TITLE
added new-articles

### PR DESCRIPTION
**Pull request by THE-AryanKumar**
@gopivaibhav added new-articles, pls review and approve... #5

### CODE REVIEW

**Comment by gopivaibhav** [comment]
Great start @THE-AryanKumar but make sure this page is responsive.

**Comment by THE-AryanKumar** [comment]
@gopivaibhav Yes sir, I made them responsive now... #8

**Comment by gopivaibhav** [comment]
> @gopivaibhav Yes sir, I made them responsive now... #8 

Nice, I will let you know if anything else is needed further with this but till then don't delete the branch in which you made these changes

**Comment by gopivaibhav** [comment]
@THE-AryanKumar We should not see this colour difference when seen with mobile. In other words, make it more responsive till the screen width of 250px

**Pull request merged**
