### PR TITLE
Team page

### PR DESCRIPTION
**Pull request by THE-AryanKumar**

### CODE REVIEW

**Comment by gopivaibhav** [comment]
Nice Cards @THE-AryanKumar 🎉

**Comment by gopivaibhav** [comment]
@THE-AryanKumar did you get some new hover effects for social media icons?
If yes, update them. Else, use the same effect and let me know after you commit the changes

**Comment by THE-AryanKumar** [comment]
@gopivaibhav Done Sir..., pls review 
#21

**Comment by gopivaibhav** [comment]
> @gopivaibhav Done Sir..., pls review #21

Increase the padding in mobile view between icons and tagline

**Comment by THE-AryanKumar** [comment]
Done sir... @gopivaibhav

**Pull request merged**
